sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 662535
  qcloud:
    regions:
    secret-id:
    secret-key:
    bucket-name:
    local-file-path:
    file-path:
